CREATE TABLE `sidebar_setting` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `president_img` VARCHAR(255) NOT NULL,
  `principal_img` VARCHAR(255) NOT NULL,
  `sub_principal_img` VARCHAR(255) NOT NULL,
  `info_img` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);
