CREATE TABLE `site_image` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `fav_icone` VARCHAR(255) NOT NULL,
  `president` VARCHAR(255) NOT NULL,
  `principal` VARCHAR(255) NOT NULL,
  `sub_principal` VARCHAR(255) NOT NULL,
  `school_logo` VARCHAR(255) NOT NULL,
  `home_bg` VARCHAR(255) NOT NULL,
  `history_bg` VARCHAR(255) NOT NULL,
  `history_font` VARCHAR(255) NOT NULL,
  `hotline` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
);
